### ISSUE TITLE
Generate file after compilation

### ISSUE THREAD

**Issue by ConAntonakos** [sagold/handlebars-webpack-plugin#10]
Is it possible to do this? The reason I'm asking is because I'm trying to integrate Subresource Integrity, and the bundled file needs to be available, and subsequently, hashed before the HTML file is generated. If not, I'll look into making a contribution.

Thanks!

**Comment by sagold** [comment]
The plugin currently is started at [compile time](https://github.com/sagold/handlebars-webpack-plugin/blob/master/index.js#L76). Maybe there is a working option for an [after-compilation-hook](https://webpack.github.io/docs/plugins.html#after-compile-async). But in the latest docs for [webpack 2](https://webpack.js.org/concepts/plugins/) options are yet missing.

- Could a separate plugin be an option for this?
- Or, if you have a working solution for loaders, this plugin is now also available as a [loader](https://github.com/sueddeutsche/handlebars-render-loader)
