### ISSUE TITLE
Partials not working with webpack

### ISSUE THREAD

**Issue by tarun-pixeleyez** [sagold/handlebars-webpack-plugin#102]
I have added webpack in my project and use this package. this works good if partial has not sub folder but if i make sub folder and create file in that then its not working.

![image](https://github.com/sagold/handlebars-webpack-plugin/assets/159905617/4b85322a-baa6-46bd-bbc4-71f9e72ba462)

![image](https://github.com/sagold/handlebars-webpack-plugin/assets/159905617/ac39ed70-c305-42ca-8675-19e151f698b9)

![image](https://github.com/sagold/handlebars-webpack-plugin/assets/159905617/83db7937-6b7f-4915-a482-a4ef157fa283)

In this code customizer, footer and its works but in chat folder sidebar not working.

**Comment by sagold** [comment]
Probably because you do not include the chat folder. Can you try `partials/*/*.html` or `partials/**/*.html`

**Comment by tarun-pixeleyez** [comment]
> Probably because you do not include the chat folder. Can you try `partials/*/*.html` or `partials/**/*.html`

Yes I have tried that but not working.

**Comment by xavierfoucrier** [comment]
Hi all 👋 

Something like this works great:

```js
partials: [
  path.resolve('src/components/**/*.hbs'),
],
```

```hbs
{{> components/main }}
{{> main/element }}
```

> Please note that it's not needed to write the whole path when templating nested elements.
