### ISSUE TITLE
Render dynamic partial?

### ISSUE THREAD

**Issue by cloudnine-gjacob** [sagold/handlebars-webpack-plugin#11]
hello!
is there any way of rendering dynamic partials as described in the docs:

`{{> (whichPartial) }}`
or 
`{{> (lookup . 'myVariable') }}`

?

**Comment by cloudnine-gjacob** [comment]
Actually the solution was pretty simple:
the lookup helper works as expected, my passed var was wrong; i had the suffix in it ".svg".
if you pass "partialsFolder/file" it works! yay

**Comment by sagold** [comment]
Hi gjacob.

Thank you dor posting the solution!
