### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by daveferrara1** [sagold/handlebars-webpack-plugin#12]
I've got this in my config:

```
// data passed to main hbs template: `main-template(data)`
    data: require("./public/build/manifest.json"),
```

I can't seem to access the data in an .hbs file. I'd prefer to get at the data in a helper.  I am looking to parse that json in a helper and write some script tags.

Do you have an example using `data:` ?

**Comment by daveferrara1** [comment]
Wondering also if I were to use something like 
```
onBeforeSetup: function (Handlebars) {
      title: 'test'
    },
```
It does not seem to be available like `{{HandlebarsPlugin.title}}`
Is there a way to do that?

**Comment by sagold** [comment]
Hi daveferrara.

The data is simply [passed to the template function](https://github.com/sagold/handlebars-webpack-plugin/blob/master/index.js#L103) as explained in the [handlebars docs](http://handlebarsjs.com/execution.html). To access the data within a helper you have two options:

1. Pass the data to a [helper directly](http://handlebarsjs.com/#helpers) (recommended): `{{myhelper dataInScope}}` or
2. Bind the data via scope to your helper

To bind the data in `webpack.config`

```js
const data = require("./public/build/manifest.json");
// ...
plugins: [
        new HandlebarsPlugin({
            data,
            helpers: {
                myhelper: function () {
                    // access data
                }
            }
        })
```

**Comment by Pieter-Rees** [comment]
Thank you for the answer 👍

**Comment by daveferrara1** [comment]
@sagold Thanks.
