### ISSUE TITLE
Not compiling when updating partials

### ISSUE THREAD

**Issue by asotog** [sagold/handlebars-webpack-plugin#19]
To make it work need to re run `webpack-dev-server --port 9000 --host 0.0.0.0;` again, this issue started when updated handlebars and webpack version not sure what happens, please see this screenshot for versions:

<img width="355" alt="screen shot 2017-05-04 at 9 09 14 am" src="https://cloud.githubusercontent.com/assets/813023/25710487/9b742b8e-30a9-11e7-822e-3b898c8afb06.png">

**Comment by asotog** [comment]
UPDATE: reverted to 0.1.1 its working now, can you please provide feedback on what happened or if new version needs another flag in configuration ?

**Comment by gavro** [comment]
Confirmed, same thing is happening here. While running ```npm run watch``` partials are not being updated. Needed to revert to v0.2.0 (needed entry files globbing).

**Comment by sagold** [comment]
With version [v1.1.0](https://github.com/sagold/handlebars-webpack-plugin/tree/v1.1.0) partials are watched and wds loads the changes. Additionally, the generated html files are served.

I hope the changes work as expected. Glad to get some confirmation.

Thanks for your feedback.
sagold

**Comment by asotog** [comment]
Thanks so much working pretty good
