### ISSUE TITLE
Run `npm publish` so that new installs have optional partials commit

### ISSUE THREAD

**Issue by DannyDelott** [sagold/handlebars-webpack-plugin#2]
Looks like the git repo and the npm module are out of sync. 

@sagold, Please run `npm publish` so that c6851e5 exists in the npm registry.

**Comment by sagold** [comment]
Hi Danny.

Has been published to v0.1.0, your PR is included. To forget to change any `helper` options to `helpers` (https://github.com/sagold/handlebars-webpack-plugin/issues/1).

Regards.
