### ISSUE TITLE
Issue in node 4

### ISSUE THREAD

**Issue by mAAdhaTTah** [sagold/handlebars-webpack-plugin#21]
Getting this error in node 4:

```js
class HandlebarsPlugin {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

Can we add a `'use strict';` to the top of the file?

**Comment by sagold** [comment]
I am hesitant to readd es5 statements to the current es6-version of the plugin. The active LTS of the node 4 has also ended. Additionally, i fear issues using the `"use strict"` statement for combinations like _visual studio code + eslint` and whatnot.

Is there any change you can work with version `v0.2.0` of this plugin? If not, we could work out a separate branch for this.

Regards.
sagold
