### ISSUE TITLE
Files being written twice

### ISSUE THREAD

**Issue by jaketodaro** [sagold/handlebars-webpack-plugin#22]
If the `output` dir is set to be a nested folder, then the compiled output will be written to the file system twice, once in the specified nested location, and once at the root. For example

```
new HandlebarsPlugin({
    entry: 'src/index.hbs',
    output: 'dist/pages/[name].html'),
}),
```

Will result in a `dist` directory that looks like

```
dist
    index.html
    pages
        index.html
```

This seems to be because the plugin is [writing the file](https://github.com/sagold/handlebars-webpack-plugin/blob/master/index.js#L180) and then [registers a generated file](https://github.com/sagold/handlebars-webpack-plugin/blob/master/index.js#L183) with webpack, which will write it again in the output root of your webpack config.

**Comment by sagold** [comment]
Hi jaketodaro.

Thanks for the input. I will look into this (probably this year).

Regards.
sagold

PS: Ever considered the [handlebars-render-loader](https://github.com/sueddeutsche/handlebars-render-loader)? I find it strange that this plugin is preferred over the loader.

**Comment by janrembold** [comment]
I just experienced the same behavior. It would be great to fix that or at least optionally disable this feature.

Will have a look into the handlebars-render-loader as well...

**Comment by gianpesto** [comment]
any news on this?

**Comment by sagold** [comment]
Hi there.

With version `1.3.1` files are only emitted once.

Regards.
