### ISSUE TITLE
generate with entries across multiple directories

### ISSUE THREAD

**Issue by leshuis** [sagold/handlebars-webpack-plugin#36]
I would - because of the number of files - to divide them into several directories en get the same structure on the business end - read output - 

Is this possible, 
and if:yes how ??

**Comment by sagold** [comment]
Hi.

This is currently not possible. Some changes [here](https://github.com/sagold/handlebars-webpack-plugin/blob/master/index.js#L18) could make that work.

**Comment by sagold** [comment]
A `[path]` option is now supported in the output directory, which maintains the folder structure of your entry files https://github.com/sagold/handlebars-webpack-plugin#usage
