### ISSUE TITLE
Problem with output

### ISSUE THREAD

**Issue by dgateles** [sagold/handlebars-webpack-plugin#47]
If i write 
`
output: path.join(process.cwd(), "build", "[name].html"),
`

My output is: 

> build/index.html; 
> build/page1.html; 
> build/page2.html

Also, if i ommit this line, my output is: 

> src/index; 
> src/pages/page1; 
> src/pages/page2

I would like to output like that:

> build/index.html; 
> build/pages/page1.html; 
> build/pages/page2.html

how to do that?

**Comment by sagold** [comment]
Hi. 

Did you try something like https://github.com/gregnb/filemanager-webpack-plugin to setup the file structure you need? `handlebars-webpack-plugin` does currently not support this.

**Comment by sagold** [comment]
Ok, thanks to @TheReincarnator, with version 1.6 there is an option `getTargetFilepath`. Here you can specify you [custom filepath generator for the html-results](https://github.com/sagold/handlebars-webpack-plugin#target-filepaths). This might help your issue.

Cheers.
