### ISSUE TITLE
Watch on Windows HBS

### ISSUE THREAD

**Issue by jagmitg** [sagold/handlebars-webpack-plugin#53]
Watch seems to be working on js, scss and html files but it keeps ignoring the hbs files within the plugin itself.

Tried the new updated version with windows santize fix but that is not working for windows.

Any suggestions or recommendations?

**Comment by sagold** [comment]
Hi @jagmitg.

I currently have no windows virtual machine running to debug this issue. Maybe some developer using windows could help.

Do you get any error messages?

**Comment by jagmitg** [comment]
@sagold - i've fixed this now utilising the paths. I can get a PR ready for review.

**Comment by sagold** [comment]
Fixed by https://github.com/sagold/handlebars-webpack-plugin/pull/63 and released with `v1.8.1`
