### ISSUE TITLE
Handlebars-webpack-plugin results in comma appended *.yml file for a JSON source.

### ISSUE THREAD

**Issue by knightswatch3** [sagold/handlebars-webpack-plugin#61]
![image](https://user-images.githubusercontent.com/9092073/72378203-c7fe2400-36c5-11ea-92ac-757322d247c0.png)

That is my JSON file as a source for templating.

 
![image](https://user-images.githubusercontent.com/9092073/72378337-07c50b80-36c6-11ea-89a6-6b878c46ced1.png)

My resultant *.yml file has the commas appended at the end of it which is no-way useful to me.

**Comment by sagold** [comment]
Hi.

Whats your webpack-config. What are you trying to accomplish. Do you generate yml-files?
