### ISSUE TITLE
(Option to) Create new Handlebars instance per plugin instance

### ISSUE THREAD

**Issue by alexschlueter** [sagold/handlebars-webpack-plugin#62]
Hi, I'm trying to use multiple webpack targets and change a helper based on a variable:

###### webpack.config.js
```javascript
const HandlebarsPlugin = require("handlebars-webpack-plugin");

const configForLang = lang => {
  return {
    mode: "development",
    plugins: [

      new HandlebarsPlugin({
        entry: "./index.hbs",
        output: `./dist/[name]_${lang}.html`,
        data: {
          "welcome": {
            "en": "Welcome to my site!",
            "de": "Willkommen zu meiner Seite!"
          }
        },
        helpers: {
          translate: obj => obj[lang]
        }
      })
    ]
  };
};

module.exports = [configForLang("en"), configForLang("de")];
```
###### index.hbs
```html
<h1>{{translate welcome}}</h1>
```

 This is currently not possible, since you are using the same global Handlebars instance for every plugin instance and helpers are just overridden:
```
HandlebarsPlugin: + helper 'translate'
HandlebarsPlugin: The helper 'translate' is already registered.
            Remove duplications to prevent hard to find errors.
```
 A solution to this would be to call `this.Handlebars = Handlebars.create()` in the constructor of `HandlebarsPlugin` and then use this local instance in the rest of the methods.
Would you be willing to add an option for this?

**Comment by sagold** [comment]
Yes indeed. This should actually be the default. It will be a breaking change, but fast to implement, since Handelbars is only required once.

**Comment by sagold** [comment]
If you like, checkout the following branch and test your setup: https://github.com/sagold/handlebars-webpack-plugin/tree/issue-62-handlebars-instances

**Comment by alexschlueter** [comment]
Thank you, works for me! There's a slight problem now if you want to have access to the Handlebars instance from a helper, since you can no longer do this:
```javascript
helpers: {
  translate: arg => {
    if (typeof arg === "string") {
      var HB = HandlebarsPlugin.Handlebars; // not the correct instance used by plugin
      return HB.compile(HB.partials[path.join(arg, lang)])();
    } else {
      return arg[lang];
    }
  }
}
```
However, I was able to get around this by registering my helper inside `onBeforeSetup`, where the actual Handlebars instance is made available by the argument:
```javascript
onBeforeSetup: HB => {
  HB.registerHelper("translate", arg => {
    if (typeof arg === "string") {
      return HB.compile(HB.partials[path.join(arg, lang)])();
    } else {
      return arg[lang];
    }
  });
},
```
