### ISSUE TITLE
Can't add partial path that is sub-folder where of entry point

### ISSUE THREAD

**Issue by raypatterson** [sagold/handlebars-webpack-plugin#64]
I have a project with a set of files like:

```sh
src
└── pages
    ├── index.hbs
    └── partials
        └── section-1.hbs
```

The plugin config looks like:

```js
new HandlebarsPlugin({
    entry: "src/pages/**/index.hbs",
    partials: [
      "src/pages/**/!(index).hbs"
    ]
  });
```

The partial `section-1.hbs` is added but I see the error:

```sh
ERROR  [
  'src/pages/index.hbs: is ignored'
]
```

It appears this LOC evaluates to `true` because the partial file path and the entry file path share a common, parent folder, `pages`.

https://github.com/sagold/handlebars-webpack-plugin/blob/b8c7af5106c8f5d3b49428c4cd450ea11e4f8e67/utils/getRootFolder.js#L30

I'm wondering if there is some way to preserve this folder structure and also avoid this error.

Please let me know if I can provide any more information. Thanks!

**Comment by sagold** [comment]
Hi raypatterson.

Thank you, for the detailed issue description. The mentioned check came in from a pr and i have neither tests, nor documentation for this. If you like, tryout the branch [issue-64-entry-within-partials](https://github.com/sagold/handlebars-webpack-plugin/tree/issue-64-entry-within-partials). This might solve your issue.

I currently have no time retracing the requirements for the removed check.

**Comment by raypatterson** [comment]
Works! The changes in the branch make it so partials can exist in sub-folders where entry points also exist.

**Comment by raypatterson** [comment]
@sagold thanks for fixing this. Is there anything I can do to help get it into a PR?

**Comment by raypatterson** [comment]
@sagold just checking back in on this one since it looks like your fix is solid, and could be good to go? Thanks again!

**Comment by sagold** [comment]
Hi Ray.

Thank you for the constant reminders. I finally merged this branch and published the package with version v2.0.0.

Cheers,
sagold

**Comment by raypatterson** [comment]
Amazing, thanks so much! 

As an aside, I'm also looking forward to the release of https://github.com/sagold/handlebars-webpack-plugin/issues/62

**Comment by sagold** [comment]
This pr should be within v2.0.0 release.
I will confirm this in two days.

**Comment by raypatterson** [comment]
Double amazing! Thanks again!
