### ISSUE TITLE
Required .hbs extension for partials

### ISSUE THREAD

**Issue by duncanwerner** [sagold/handlebars-webpack-plugin#7]
I want to use partials as includes, but I don't (necessary) want to use the .hbs extension, at least while I'm transitioning.  This extension is required by the regex in getPartialId().

I'm not sure if this is something that you want to fix, but changing the regex will work the same way for any extension (although an extension is still required):

```
function getPartialId(path) {
  return path.match(/\/([^\/]+\/[^\/]+)\.[^\.]+$/).pop();
}
```

**Comment by sagold** [comment]
Hey duncan, I changed the regex in 8f68abe361d17e92b61ff37a2b0506ed1d1688d3.
Thanks for the feedback.
