### ISSUE TITLE
Editing helper code doesn't make any change in output until restart

### ISSUE THREAD

**Issue by 5ulo** [sagold/handlebars-webpack-plugin#72]
After saving changes in helper file the webpack-dev-server compiles and reloads as usually, but the changes aren't visible until I manually stop webpack-dev-server and run it again. It's a bit uncomfortable while writing custom helper from scratch.

Is there any option that watches any helper change? Helper editing and reloading is working with `handlebars-loader` which I don't want to use.
note: reload on hbs files works perfectly. Thanks

```javascript
module.exports = (env, argv) => {
    return {
        plugins: [
            new HandlebarsPlugin({
                helpers: {
                    projectHelpers: path.join(dirHelpers, "*.js")
                },
            }),
        ]
    }
};
```

**Comment by sagold** [comment]
Which operating system are you using?

**Comment by 5ulo** [comment]
MacOs

**Comment by sagold** [comment]
I can confirm this and will look into it. The change is recognized, but the new result is not emitted.

**Comment by sagold** [comment]
A fix is published with `v2.1.1`. Does this work for you?

**Comment by 5ulo** [comment]
@sagold Yes, `v2.1.1` fixed this issue. Perfect job!

**Comment by 5ulo** [comment]
So.. this is weird, I haven't noticed it before.. website reloads on partial, layout, helper change, but does not reload on page change. Change is recognised, I see it in the console.
