### ISSUE TITLE
Html-webpack-plugin peerDependency out of date

### ISSUE THREAD

**Issue by detrohutt** [sagold/handlebars-webpack-plugin#85]
Hello, and thanks for this plugin. Html-webpack-plugin is on v5.x now. Would you please update your peerDependency to allow the new versions (assuming it is compatible)? Thanks!

**Comment by chaoticvibe** [comment]
Yeah i had the same problem...

**Comment by xavierfoucrier** [comment]
Hi everyone,

It's a duplicate of https://github.com/sagold/handlebars-webpack-plugin/issues/78.
