### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by rowild** [sagold/handlebars-webpack-plugin#96]
Webpack has moved on and still is. Any chance to update this plugin?

**Comment by Poylar** [comment]
guess better use HTMLWebpackPlugin with hbs-loader

**Comment by webdiscus** [comment]
The HTMLWebpackPlugin is not maintained over a year too.

Better try to use new modern powerful [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin).

This plugin support many templating engines "out of the box":
- Handlebars
- EJS
- Eta
- Nunjucks
